name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
    env:
      - IMAGE_TAG: latest
  pull_request:
    branches: [ "dev" ]
    env:
      - IMAGE_TAG: $(git rev-parse --short "$GITHUB_SHA")

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/fcorso2016/mkxp-z:$IMAGE_TAG

    - name: Publish Docker Image
      run: docker push ghcr.io/fcorso2016/mkxp-z:$IMAGE_TAG
